exec-once = waybar 
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "everforest-gtk" 
exec-once = gsettings set org.gnome.desktop.interface font-name "Mononoki Nerd Font 12"
exec-once = swaybg -i ~/.config/hypr/car2.png
exec-once = swayidle -w timeout 300 'swaylock -f -i ~/.config/hypr/car2.png'  timeout 600 'swaymsg "output eDP-1 dpms off"' resume 'swaymsg "output eDP-1 dpms on"' timeout 660 'systemctl suspend' after-resume 'swaymsg "output * dpms on"'
exec-once = sway-audio-idle-inhibit


monitor = DP-4, 1920x1080, 0x0, 1
monitor = DP-3, 1920x1080, 1920x0, 1

general {
    border_size = 3
    gaps_in = 5
    gaps_out = 10

    col.inactive_border = rgb(2d353b) 
    col.active_border = rgb(a7c080)


    resize_on_border = true
    extend_border_grab_area = true
    hover_icon_on_border = true
}

decoration {
    active_opacity = 1
    inactive_opacity = 1
    fullscreen_opacity = 1

    drop_shadow = true 
    shadow_range = 4
    shadow_render_power = 3

    blur {
        enabled = false
        size = 9
        passes = 2
    }
}

gestures {
    workspace_swipe = true
    workspace_swipe_fingers = 3

    workspace_swipe_forever = true
}

misc {
    disable_hyprland_logo = true 
    animate_manual_resizes = true
    animate_mouse_windowdragging = true
}


bind = SUPER, RETURN, exec, alacritty 
bind = SUPER, D, exec, rofi -show drun
bind = SUPER_SHIFT, Q, killactive,
bind = SUPER_SHIFT, E, exit,
bind = SUPER, L, exec, swaylock -i ~/.config/hypr/car2.png

bind = SUPER_SHIFT, SPACE, togglefloating,
bind = SUPER, P, pin,

bind = SUPER, F, fullscreen,

bind = SUPER, 0, workspace, 0
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9

bind = SUPER_SHIFT, 0, movetoworkspace, 0
bind = SUPER_SHIFT, 1, movetoworkspace, 1
bind = SUPER_SHIFT, 2, movetoworkspace, 2
bind = SUPER_SHIFT, 3, movetoworkspace, 3
bind = SUPER_SHIFT, 4, movetoworkspace, 4
bind = SUPER_SHIFT, 5, movetoworkspace, 5
bind = SUPER_SHIFT, 6, movetoworkspace, 6
bind = SUPER_SHIFT, 7, movetoworkspace, 7
bind = SUPER_SHIFT, 8, movetoworkspace, 8
bind = SUPER_SHIFT, 9, movetoworkspace, 9

bind = SUPER, mouse_down, workspace, e+1
bind = SUPER, mouse_up, workspace, e-1

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d

bind = SUPER, P, pseudo, 
bind = SUPER, J, togglesplit,

bindl = ,switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, 1920x1080, 0x0, 0.9"
bindl = ,switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-1, disable" 

binde =, XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindl =, XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind =, XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind =, XF86AudioPlay, exec, playerctl play-pause
bind =, XF86AudioNext, exec, playerctl next
bind =, XF86AudioPrev, exec, playerctl previous
bind = SUPER_SHIFT, P, exec, playerctl play-pause

binde =, XF86MonBrightnessDown, exec, light -U 5%
bindl =, XF86MonBrightnessUp, exec, light -A 5%
